server:
  port: 8081
logging:
  level:
    '[com.fffattiger.wechatbot]': INFO
spring:
  ai:
    model:
      audio:
        speech: NONE
        transcription: NONE
      embedding: NONE
      image: NONE
      moderation: NONE
      chat: NONE
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
      client:
        enabled: false
  datasource:
    url: jdbc:postgresql://192.168.31.66:5437/postgres
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver

chatbot:
  # 聊天记录API地址
  chatLogApiUrl: http://192.168.31.77:5030
  # 微信网关基础URL
  wx-auto-gateway-http-url: http://192.168.31.77:8000
  wx-auto-gateway-ws-url: ws://192.168.31.77:8765
  # 数据库初始化配置
  database:
    init:
      enabled: true  # 是否启用数据库初始化检查
      force-recreate: false  # 是否强制重新创建表（慎用）