server:
  port: 8080 
#logging:
#  level:
#    '[com.fffattiger.wechatbot]': DEBUG
        
spring:
  ai:
    deepseek:
      chat:
        api-key: sk-xxxxxxx
chatbot:
  # 聊天记录API地址
  chatLogApiUrl: http://127.0.0.1:5030
  # 微信网关基础URL
  wx-auto-gateway-http-url: http://127.0.0.1:8000
  wx-auto-gateway-ws-url: http://127.0.0.1:8765
  # 监听的微信窗口对象
  listeners:
    - wxInfo:
        # 微信窗口名称
        chatName: 测试一号
        # 是否是群聊
        groupFlg: true
      # 是否开启@回复
      at-reply-enable: true
      # 允许的命令
      command-info:
        # 允许的命令通配符
        allow-command-patterns:
          - - '/*'
        # 允许的命令用户
        command-allow-user:
          '[/*]':
            - 'fffattiger'
    - wxInfo:
        chatName: 测试二号
        groupFlg: true
      at-reply-enable: true
      command-info:
        allow-command-patterns:
        - '/*'
        command-allow-user:
          '[/*]':
            - 'fffattiger'
