server:
  port: 8080 
logging:
  level:
    '[com.fffattiger.wechatbot]': DEBUG
spring:
  ai:
    model:
      audio:
        speech: NONE
        transcription: NONE
      embedding: NONE
      image: NONE
      moderation: NONE
      chat: NONE
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
      client:
        enabled: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    url: jdbc:postgresql://192.168.31.66:5437/tigerbot
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver

chatbot:
  # 聊天记录API地址
  chatLogApiUrl: http://192.168.31.77:5030
  # 微信网关基础URL
  wx-auto-gateway-http-url: http://192.168.31.77:8000
  wx-auto-gateway-ws-url: ws://192.168.31.77:8765
  # 数据库初始化配置
  database:
    init:
      enabled: true  # 是否启用数据库初始化检查
      force-recreate: false  # 是否强制重新创建表（慎用）
  robot-name: hcuu
  proxy:
    enabled: true  # 是否启用代理
    host: 192.168.31.88  # 代理主机地址
    port: 7890  # 代理端口
    type: HTTP  # 代理类型：HTTP 或 SOCKS

cloudpaste:
  base-backend-url: https://paster.qoq.icu/
  base-frontend-url: https://p.qoq.icu/
  api-token: Am2VbyKN14gD
  connect-timeout: 5000
  read-timeout: 100000
